import { createClient } from '@supabase/supabase-js'
import ResultClient from './ResultClient'
import Nav from '../../../components/Nav'
import Footer from '../../../components/Footer'
import { notFound } from 'next/navigation'

function getSupabase() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key || url === 'your_supabase_url_here') return null
  return createClient(url, key)
}

export async function generateMetadata({ params }) {
  const { slug } = await params
  const supabase = getSupabase()
  if (!supabase) return { title: 'Risk analysis — De-Risk Matrix' }
  const { data } = await supabase.from('website_analyses').select('company_name, industry').eq('slug', slug).single()
  if (!data) return { title: 'Risk analysis — De-Risk Matrix' }
  return {
    title: `Risk picture for ${data.company_name} — De-Risk Matrix`,
    description: `Suggested goals, thresholds, and predicted risk states for ${data.company_name}. Industry: ${data.industry}.`,
    openGraph: {
      title: `Risk picture for ${data.company_name}`,
      description: `See which goals are at risk for ${data.company_name} — generated by De-Risk Matrix.`,
      url: `https://www.deriskmatrix.com/analysis/${slug}`,
    },
  }
}

export default async function AnalysisPage({ params, searchParams }) {
  const { slug } = await params
  const { mode } = await searchParams || {}
  const supabase = getSupabase()

  if (!supabase) {
    // Graceful fallback if env vars not set
    return (
      <>
        <Nav />
        <div className="min-h-screen flex items-center justify-center">
          <div className="text-center">
            <h1 className="text-2xl font-bold text-navy mb-4">Configuration required</h1>
            <p className="text-slate-500">Please configure Supabase environment variables.</p>
          </div>
        </div>
        <Footer />
      </>
    )
  }

  const { data: analysis } = await supabase
    .from('website_analyses')
    .select('*')
    .eq('slug', slug)
    .single()

  if (!analysis) notFound()

  return (
    <>
      <Nav />
      <ResultClient analysis={analysis} mode={mode || 'company'} />
      <Footer />
    </>
  )
}
